services:
  postgres:
    image: postgres:16
    container_name: uce_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: uce
      POSTGRES_PASSWORD: uce123
      POSTGRES_DB: uce_tramites
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: uce_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: uce_rabbit
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: uce_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: uce_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo:
    image: mongo:7
    container_name: uce_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build:
      context: ../apps/auth-service
    container_name: auth_service
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      APP_ENV: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: uce_tramites
      DB_USER: uce
      DB_PASS: uce123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP: kafka:9092
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - postgres
      - redis
      - kafka
      - rabbitmq

  tramites-service:
    build:
      context: ../apps/tramites-service
    container_name: tramites_service
    restart: unless-stopped
    ports:
      - "8002:8000"
    environment:
      APP_ENV: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: uce_tramites
      DB_USER: uce
      DB_PASS: uce123
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC: tramite.creado
    depends_on:
      - postgres
      - kafka

  workflow-service:
    build:
      context: ../apps/workflow-service
    container_name: workflow_service
    restart: unless-stopped
    environment:
      APP_ENV: local
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC: tramite.creado
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: uce_tramites
      DB_USER: uce
      DB_PASS: uce123
    depends_on:
      - kafka
      - postgres

  documents-service:
    build:
      context: ../apps/documents-service
    container_name: documents_service
    restart: unless-stopped
    ports:
      - "8003:8000"
    environment:
      APP_ENV: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: uce_tramites
      DB_USER: uce
      DB_PASS: uce123
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC: documento.subido
    depends_on:
      - postgres
      - kafka

  # 5to microservicio: notifications-service
  notifications-service:
    build:
      context: ../apps/notifications-service
    container_name: notifications_service
    restart: unless-stopped
    ports:
      - "8004:8000"
    environment:
      APP_ENV: local
      PYTHONUNBUFFERED: "1"
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPICS: "tramite.creado,documento.subido,payments.events"
    depends_on:
      - kafka

  # 6to microservicio: audit-service
  audit-service:
    build:
      context: ../apps/audit-service
    container_name: audit_service
    restart: unless-stopped
    ports:
      - "8005:8000"
    environment:
      APP_ENV: local
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPICS: "tramite.creado,documento.subido"
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: uce_audit
      MONGO_COLLECTION: events
    depends_on:
      - kafka
      - mongo

  # 7mo microservicio: payments-service
  payments-service:
    build:
      context: ../apps/payments-service
    container_name: payments_service
    restart: unless-stopped
    ports:
      - "8006:8000"
    environment:
      APP_ENV: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: uce_tramites
      DB_USER: uce
      DB_PASS: uce123
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC: "payments.events"
    depends_on:
      - postgres
      - kafka

  users-service:
    build:
      context: ../apps/users-service
    container_name: users_service
    restart: unless-stopped
    ports:
      - "8007:8000"
    environment:
      APP_ENV: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: uce_tramites
      DB_USER: uce
      DB_PASS: uce123
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC: "users.events"
    depends_on:
      - postgres
      - kafka




  students-service:
    build:
      context: ../apps/students-service
    container_name: students_service
    restart: unless-stopped
    ports:
      - "8008:8000"
    environment:
      APP_ENV: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: uce_tramites
      DB_USER: uce
      DB_PASS: uce123
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC: "students.events"
    depends_on:
      - postgres
      - kafka

  reporting-service:
    build:
      context: ../apps/reporting-service
    container_name: reporting_service
    restart: unless-stopped
    ports:
      - "8010:8000"
    environment:
      APP_ENV: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: uce_tramites
      DB_USER: uce
      DB_PASS: uce123
      KAFKA_BOOTSTRAP: kafka:9092
    depends_on:
      - postgres
      - kafka



volumes:
  postgres_data:
  mongo_data:
