server {
  listen 80;

  location /health { return 200 "ok\n"; }

  location /auth/         { proxy_pass http://auth_service:8000/; }
  location /tramites/     { proxy_pass http://tramites_service:8000/; }
  location /workflow/     { proxy_pass http://workflow_service:8000/; }
  location /documents/    { proxy_pass http://documents_service:8000/; }
  location /notifications/{ proxy_pass http://notifications_service:8000/; }
  location /audit/        { proxy_pass http://audit_service:8000/; }
  location /payments/     { proxy_pass http://payments_service:8000/; }
  location /users/        { proxy_pass http://users_service:8000/; }
  location /students/     { proxy_pass http://students_service:8000/; }
  location /reports/      { proxy_pass http://reporting_service:8000/; }
}
